## Pembuka

Assalamu'alaikum warahmatullahi wabarakatuh.
Puji syukur kehadirat Allah Subhana Wata'ala atas limpahan Rahmat dan HidayahNya kepada kita semua.
Sholawat serta salam senantiasa tercurah limpahkan kepada baginda Muhammad Rasulullah Salallahualaihiwassalam.

Halo para **Pejuang Data**. Selamat berjumpa di pertemuan kedelapan Program Training **Algoritma Machine Learning** Kelas Mahir. Pada model machine learning dibutuhkan variabel x atau disebut features dan variabel y yang disebut label. Kita dapat memodifikasi data teks yang kita miliki menjadi matriks yang terdiri atas variabel x dan y tersebut menggunakan beberapa model representasi teks yaitu:

1. Bag-of-Words
2. TF-IDF

Namun sebelum ke sana, ada materi dasar dulu yang perlu dipahami sebelum membahas keduanya, yaitu Tokenisasi. Kamu akan mempelajari bagaimana sebuah teks dapat dipecah menjadi kalimat dan kata-kata yang kita biasa sebut sebagai token. Setelah data teks yang kita miliki kita tokenisasi baru bisa diproses menjadi features baik itu Bag-of-Words maupun TF-IDF.

## Tokenisasi

Tokenisasi adalah pemecahan serangkaian data teks ke dalam kepingan-kepingan baik kalimat maupun kata. Pemecahan data teks menjadi kalimat biasanya ditandai dengan tanda baca pemisah titik('.'). Sedangkan, untuk pemecahan kalimat menjadi kata dapat dicontohkan sebagai berikut. Misalnya kalimat “Ini baju saya” akan menjadi “ini, baju, saya”.

### Tokenisasi Kalimat 

Kita akan mencoba memecah serangkaian data teks menjadi kalimat-kalimat. Kita dapat menggunakan function 'sent_tokenize' dari library `nltk` untuk melakukannya dengan tujuan kepraktisan.

In [33]:
import nltk
from nltk import sent_tokenize

Berikut adalah contoh paragraf yang akan kita gunakan pada notebooks ini.

In [34]:
paragraph = '''
Data science adalah topik diskusi yang sangat luas dan subyektif. Data science bukan sebuah bidang yang berdiri sendiri. Bidang ini merupakan kombinasi dari berbagai bidang termasuk Ilmu Komputer, Matematika, Statistik, dan Strategi Bisnis. Tiga komponen yang terlibat dalam data science adalah organising, packaging, dan delivering data (the OPD of data). Organising data adalah proses penyimpanan data yang digabungkan dengan manajemen data. Packaging data merupakan proses manipulasi dan penggabungan data mentah yang akan direpresentasikan. Delivering data merupakan proses untuk memastikan bahwa pesan data telah diakses oleh mereka yang memerlukannya. Menurut research tahun 2011, pada tahun 2020 dunia akan menghasilkan 50 kali lipat data dibandingkan tahun 2011. Jadi dengan peningkatan aliran data yang drastis tersebut, akan muncul alat-alat baru yang dapat digunakan untuk memanfaatkan data mentah dengan tepat. Data science mencakup semua alat, teknik, dan teknologi yang akan membantu kita menangani peningkatan aliran data tersebut. Data science merupakan perpaduan interdisipliner dari penurunan data, pengembangan algoritma, dan teknologi untuk memecahkan masalah analitik yang kompleks.
'''
paragraph

'\nData science adalah topik diskusi yang sangat luas dan subyektif. Data science bukan sebuah bidang yang berdiri sendiri. Bidang ini merupakan kombinasi dari berbagai bidang termasuk Ilmu Komputer, Matematika, Statistik, dan Strategi Bisnis. Tiga komponen yang terlibat dalam data science adalah organising, packaging, dan delivering data (the OPD of data). Organising data adalah proses penyimpanan data yang digabungkan dengan manajemen data. Packaging data merupakan proses manipulasi dan penggabungan data mentah yang akan direpresentasikan. Delivering data merupakan proses untuk memastikan bahwa pesan data telah diakses oleh mereka yang memerlukannya. Menurut research tahun 2011, pada tahun 2020 dunia akan menghasilkan 50 kali lipat data dibandingkan tahun 2011. Jadi dengan peningkatan aliran data yang drastis tersebut, akan muncul alat-alat baru yang dapat digunakan untuk memanfaatkan data mentah dengan tepat. Data science mencakup semua alat, teknik, dan teknologi yang akan membantu

Kemudian akan kita tokenisasi menjadi kalimat-kalimat sebagai berikut:

In [35]:
tokenisasi_kalimat = sent_tokenize(paragraph)
print(tokenisasi_kalimat)

['\nData science adalah topik diskusi yang sangat luas dan subyektif.', 'Data science bukan sebuah bidang yang berdiri sendiri.', 'Bidang ini merupakan kombinasi dari berbagai bidang termasuk Ilmu Komputer, Matematika, Statistik, dan Strategi Bisnis.', 'Tiga komponen yang terlibat dalam data science adalah organising, packaging, dan delivering data (the OPD of data).', 'Organising data adalah proses penyimpanan data yang digabungkan dengan manajemen data.', 'Packaging data merupakan proses manipulasi dan penggabungan data mentah yang akan direpresentasikan.', 'Delivering data merupakan proses untuk memastikan bahwa pesan data telah diakses oleh mereka yang memerlukannya.', 'Menurut research tahun 2011, pada tahun 2020 dunia akan menghasilkan 50 kali lipat data dibandingkan tahun 2011.', 'Jadi dengan peningkatan aliran data yang drastis tersebut, akan muncul alat-alat baru yang dapat digunakan untuk memanfaatkan data mentah dengan tepat.', 'Data science mencakup semua alat, teknik, dan 

Menampilkan kalimat pertama:

In [36]:
tokenisasi_kalimat[0]

'\nData science adalah topik diskusi yang sangat luas dan subyektif.'

### Tokenisasi Kata-kata

Jika tokenisasi kalimat membagi sekumpulan text menjadi beberapa kalimat dengan pemisah titik, maka tokenisasi kata-kata adalah memecah string berdasarkan spasi. Sehingga token yang dimaksud merupakan suatu kata pada sebuah kalimat. Untuk kepraktisan kita bisa menggunakan fungsi `word_tokenize` dari library `nltk` untuk melakukan hal ini.

In [37]:
import nltk
from nltk import word_tokenize

Misal kita akan memecah teks berikut menjadi tokenisasi kata-kata.

In [38]:
teks = "Assalamualaikum dan selamat pagi teman teman"
tokenisasi = word_tokenize(teks)
print(tokenisasi)

['Assalamualaikum', 'dan', 'selamat', 'pagi', 'teman', 'teman']


## Representasi Kata Menggunakan Matriks 

### Bag Of Word

Bag of word adalah metode untuk merepresentasikan kata-kata pada sebuah matriks untuk diolah pada metode NLP yang paling sederhana. Ide dasar dari metode ini adalah menghitung kemunculan sebuah kata pada sebuah kalimat tertentu. Misal dalama kalimat:

    `Selamat Pagi Matematika UAD`
    
Maka kata-kata yang muncul pada kalimat di atas adalah `Selamat`, `Pagi`, `Matematika`, dan `UAD`

Representasi ini dilambangkan dengan angka 1 yang bermakna suatu kata `muncul` dan 0 jika suatu kata `tidak muncul`

In [39]:
import pandas as pd
df=pd.DataFrame({"Selamat":[1,1], 
                 "Pagi":[1,1], 
                 "Matematika":[1,0], 
                 "UAD":[1,0], 
                 "Indonesia":[0,1]}, index=['Selamat Pagi Matematika UAD', 'Selamat Pagi Indonesia'])
df

Selamat  Pagi  Matematika  UAD  Indonesia
Selamat Pagi Matematika UAD        1     1           1    1          0
Selamat Pagi Indonesia             1     1           0    0          1

### Membuat Matriks Bag-of-Words From Scratch

Impor Modul Yang Diperlukan

In [8]:
#Impor Modul Yang Diperlukan
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize

DataFrame Teks Input

In [9]:
df_teks=pd.DataFrame({"text":['Selamat Pagi Matematika UAD','Selamat Pagi Indonesia']})
df_teks

text
0  Selamat Pagi Matematika UAD
1       Selamat Pagi Indonesia

Membuat List Kosa Kata

In [10]:
kosa_kata = set()
for i in df_teks.text:
    token_kal=set(word_tokenize(i.lower()))
    kosa_kata=set.union(kosa_kata,token_kal)
    #print(kosa_kata)
    
kosa_kata = sorted(kosa_kata)
print(kosa_kata)

# Jumlah kata-kata pada list vocab           
jumlah_kosa_kata = len(kosa_kata)
print(jumlah_kosa_kata)

['indonesia', 'matematika', 'pagi', 'selamat', 'uad']
5


Membuat Dictionary Kosa Kata Untuk Membuat Baris Kosa Kata

In [11]:
indeks_kata = {}
for kata in kosa_kata:
    indeks_kata[kata] = 0
    
print(indeks_kata)

{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}


Membuat Matriks Kata

In [12]:
vektor_kata=np.array([])
for baris_teks in df_teks.text:
    print(baris_teks)
    baris_kata = indeks_kata.copy()
    print('baris_kata', baris_kata)
    for kata in baris_teks.lower().split():
        baris_kata[kata]=+1
        print(baris_kata)
    baris_kata = np.array(list(baris_kata.values()))  
    vektor_kata = np.concatenate((vektor_kata,baris_kata), axis=0)
    print(vektor_kata)
matriks_kata = vektor_kata.reshape(df.shape[0], jumlah_kosa_kata)

Selamat Pagi Matematika UAD
baris_kata {'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 1, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 1, 'pagi': 1, 'selamat': 1, 'uad': 1}
[0. 1. 1. 1. 1.]
Selamat Pagi Indonesia
baris_kata {'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 1, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
[0. 1. 1. 1. 1. 1. 0. 1. 1. 0.]


In [13]:
print(matriks_kata)

[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 0.]]


Membuat DataFrame Bag Of Words

In [14]:
df_BoW = pd.DataFrame(matriks_kata, columns=kosa_kata, index=df_teks.text.tolist())
df_BoW = df_BoW.astype('int')
df_BoW

indonesia  matematika  pagi  selamat  uad
Selamat Pagi Matematika UAD          0           1     1        1    1
Selamat Pagi Indonesia               1           0     1        1    0

**Membuat Fungsi `Bag_Of_Words()`**

In [15]:
#Impor Modul Yang Diperlukan
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize

def Bag_Of_Words(df_teks):
    # Membuat list kosa kata dari seluruh teks input
    kosa_kata = set()
    for i in df_teks.text:
        token_kal=set(word_tokenize(i.lower()))
        kosa_kata=set.union(kosa_kata,token_kal)
    kosa_kata = sorted(kosa_kata)
    # Membuat dictionary kata-kata
    indeks_kata = {}
    for kata in kosa_kata:
        indeks_kata[kata] = 0
    # Jumlah kosa kata(untuk kolom)
    jumlah_kosa_kata = len(kosa_kata)
    # Membagun matriks kata
    vektor_kata=np.array([])
    for baris_teks in df_teks.text:
        baris_kata = indeks_kata.copy()
        for kata in baris_teks.lower().split():
            baris_kata[kata]=+1
        baris_kata = np.array(list(baris_kata.values()))  
        vektor_kata = np.concatenate((vektor_kata,baris_kata), axis=0)
    matriks_kata = vektor_kata.reshape(df_teks.shape[0], jumlah_kosa_kata)    
    df_bow = pd.DataFrame(matriks_kata, columns=kosa_kata, index=df_teks.text.tolist())
    df_bow = df_bow.astype('int')
    return df_bow

**Contoh Implementasi Fungsi `Bag_Of_Words()`**

In [16]:
df_teks

text
0  Selamat Pagi Matematika UAD
1       Selamat Pagi Indonesia

In [17]:
df_BoW=Bag_Of_Words(df_teks)
df_BoW

indonesia  matematika  pagi  selamat  uad
Selamat Pagi Matematika UAD          0           1     1        1    1
Selamat Pagi Indonesia               1           0     1        1    0

### Perbandingan dengan Scikit Learn Library

Sebenarnya, kita bisa menghasilkan matriks BoW dengan menggunakan Library Scikit Learn pada Class `CountVectorizer`

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

corpus = ['Selamat Pagi Matematika UAD','Selamat Pagi Indonesia']

X = vectorizer.fit_transform(corpus)

df_BoW_SL = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names(), index=corpus)
df_BoW_SL

indonesia  matematika  pagi  selamat  uad
Selamat Pagi Matematika UAD          0           1     1        1    1
Selamat Pagi Indonesia               1           0     1        1    0

Hasil fungsi yang kita buat dari dasar sama dengan `CountVectorizer` dari Library Scikit Learn

### Kekurangan Bag-of-Words

Meskipun model ini sangat sederhana untuk diimplementasikan, namun model ini masih memiliki bebrapa kekurangan:
    
* **Ketersebaran(Sparsity)**: Model BOW membuat vektor sparse yang meningkatkan kompleksitas ruang dan juga mempersulit algoritma prediksi kami untuk dipelajari.

* **Arti Kata**: Kata hanya direpresentasikan keberadaanya namun tidak sampai pada makna dan konteksnya dalam sebuah kalimat.

## TF-IDF

TF-IDF adalah metode untuk merepresentasikan kata-kata dalam angka. TF-IDF merupakan gabungan dari Term Frequency(TF) dan Inverse Document Frequency(IDF). 

### Term Frequency(TF)
Term Frequency(TF) merupakan frekuensi kemunculan kata i pada kalimat j dibagi dengan total kata pada kalimat j. TF mengukur seberapa sering kata muncul dalam sebuah kalimat. Masing-masing kalimat memiliki panjang(jumlah kata) yang berbeda-beda, maka pada kalimat yang lebih panjang sebuah kata bisa muncul lebih banyak dari pada kalimat yang pendek. 

$$TF(kata) = \frac{\text{Jumlah kata i muncul dalam kalimat}}{\text{Jumlah kata dalam kalimat}}$$

### Inverse Document Frequency(IDF)
Inverse Document Frequency(IDF) mengukur seberapa penting kata tersebut. Saat menghitung TF kita menganggap semua kata sama penting. Bagaimanapun kita tahu bahwa ada beberapa kata yang sering muncul namun sebenarnya tidak penting seperti `adalah`, `pada`, `ini`, dll. Maka semakin tinggi nilai IDF dari sebuah kata, semakin tidak penting pula kata tersebut dalam sebuah kalimat. Pada dasarnya IDF(kata) dihitung sebagai berikut:

$$IDF(kata) = \log_{e} \frac{\text{Jumlah kalimat}}{\text{Jumlah kalimat mengandung `kata`}}$$

untuk menghidari pembagian dengan nol maka pada bagian penyebut ditambah 1

$$IDF(kata) = \log_{e} \frac{\text{1 + Jumlah kalimat}}{\text{1 + Jumlah kalimat mengandung `kata`}} + 1$$

### Contoh Penghitungan Manual TF-IDF

<table>
  <tr><td>
    <img src="TF IDF.png">
  </td></tr>
<table>

### Membuat Matriks TF-IDF From Scratch

Impor Modul Yang Diperlukan

In [19]:
#Impor Modul Yang Diperlukan
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
import math
from sklearn.preprocessing import normalize

DataFrame Teks Input

In [20]:
df_teks=pd.DataFrame({"text":['Selamat Pagi Matematika UAD','Selamat Pagi Indonesia']})
df_teks

text
0  Selamat Pagi Matematika UAD
1       Selamat Pagi Indonesia

Membuat List Kosa Kata

In [21]:
kosa_kata = set()
for i in df_teks.text:
    token_kal=set(word_tokenize(i.lower()))
    kosa_kata=set.union(kosa_kata,token_kal)
    #print(kosa_kata)
    
kosa_kata = sorted(kosa_kata)
print(kosa_kata)

# Jumlah kata-kata pada list vocab           
jumlah_kosa_kata = len(kosa_kata)
print(jumlah_kosa_kata)

['indonesia', 'matematika', 'pagi', 'selamat', 'uad']
5


Membuat Dictionary Kosa Kata Untuk Membuat Baris Kosa Kata

In [22]:
indeks_kata = {}
for kata in kosa_kata:
    indeks_kata[kata] = 0
    
print(indeks_kata)

{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}


Membuat Matriks TF

In [23]:
vektor_TF=np.array([])
for baris_teks in df_teks.text:
    print(baris_teks)
    baris_kata = indeks_kata.copy()
    print('baris_kata', baris_kata)
    split_baris = baris_teks.lower().split()
    for kata in baris_teks.lower().split():
        baris_kata[kata]=+1
        print(baris_kata)
    baris_kata = np.array(list(baris_kata.values()))
    baris_kata = baris_kata/len(split_baris)
    vektor_TF = np.concatenate((vektor_TF,baris_kata), axis=0)
    print(vektor_TF)
matriks_TF = vektor_TF.reshape(df_teks.shape[0], jumlah_kosa_kata)

Selamat Pagi Matematika UAD
baris_kata {'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 1, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 1, 'pagi': 1, 'selamat': 1, 'uad': 1}
[0.   0.25 0.25 0.25 0.25]
Selamat Pagi Indonesia
baris_kata {'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 0, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 0, 'selamat': 1, 'uad': 0}
{'indonesia': 0, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
{'indonesia': 1, 'matematika': 0, 'pagi': 1, 'selamat': 1, 'uad': 0}
[0.         0.25       0.25       0.25       0.25       0.33333333
 0.         0.33333333 0.33333333 0.        ]


In [24]:
print(matriks_TF)

[[0.         0.25       0.25       0.25       0.25      ]
 [0.33333333 0.         0.33333333 0.33333333 0.        ]]


In [25]:
df_TF = pd.DataFrame(matriks_TF, columns=kosa_kata, index=df_teks.text.tolist())
df_TF

indonesia  matematika      pagi   selamat   uad
Selamat Pagi Matematika UAD   0.000000        0.25  0.250000  0.250000  0.25
Selamat Pagi Indonesia        0.333333        0.00  0.333333  0.333333  0.00

Membuat Baris IDF

In [26]:
baris_IDF=[]
for kolom in df_TF.columns :
    N = len(df_teks.text)
    kal_kata = len(df_TF[df_TF[kolom]>0])
    baris_idf = (math.log((1+N)/(1+kal_kata)))+1  
    baris_IDF.append(baris_idf)
baris_IDF

[1.4054651081081644, 1.4054651081081644, 1.0, 1.0, 1.4054651081081644]

Membuat Matriks TF-IDF

In [27]:
vektor_TFIDF=np.array([])
for baris in matriks_TF:
    baris_tfidf=np.multiply(baris,baris_IDF)
    vektor_TFIDF=np.concatenate((vektor_TFIDF,baris_tfidf), axis=0)
    
matriks_TFIDF = vektor_TFIDF.reshape(df_teks.shape[0], jumlah_kosa_kata)
matriks_TFIDF = normalize(matriks_TFIDF)

Membuat DataFrame TFIDF

In [28]:
df_TF_IDF = pd.DataFrame(matriks_TFIDF, columns=kosa_kata, index=df_teks.text.tolist())
df_TF_IDF

indonesia  matematika      pagi   selamat  \
Selamat Pagi Matematika UAD   0.000000    0.576152  0.409937  0.409937   
Selamat Pagi Indonesia        0.704909    0.000000  0.501549  0.501549   

                                  uad  
Selamat Pagi Matematika UAD  0.576152  
Selamat Pagi Indonesia       0.000000

**Membuat Fungsi `TFIDF()`**

In [29]:
#Impor Modul Yang Diperlukan
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
import math
from sklearn.preprocessing import normalize

def TF_IDF(df_teks):
    # Membuat list kosa kata dari seluruh teks input
    kosa_kata = set()
    for i in df_teks.text:
        token_kal=set(word_tokenize(i.lower()))
        kosa_kata=set.union(kosa_kata,token_kal)
    kosa_kata = sorted(kosa_kata)
    # Membuat dictionary kata-kata
    indeks_kata = {}
    for kata in kosa_kata:
        indeks_kata[kata] = 0
    # Jumlah kosa kata(untuk kolom)
    jumlah_kosa_kata = len(kosa_kata)
    # Membagun matriks kata TF
    vektor_TF=np.array([])
    for baris_teks in df_teks.text:
        baris_kata = indeks_kata.copy()
        split_baris = baris_teks.lower().split()
        for kata in baris_teks.lower().split():
            baris_kata[kata]=+1
        baris_kata = np.array(list(baris_kata.values()))
        baris_kata = baris_kata/len(split_baris)
        vektor_TF = np.concatenate((vektor_TF,baris_kata), axis=0)
    matriks_TF = vektor_TF.reshape(df_teks.shape[0], jumlah_kosa_kata)
    # Membagun dataframe kata TF
    df_TF = pd.DataFrame(matriks_TF, columns=kosa_kata, index=df_teks.text.tolist())
    # Menghitung baris IDF
    baris_IDF=[]
    for kolom in df_TF.columns :
        N = len(df_teks.text)
        kal_kata = len(df_TF[df_TF[kolom]>0])
        baris_idf = (math.log((1+N)/(1+kal_kata)))+1  
        baris_IDF.append(baris_idf)
    # Membuat matriks TF-IDF
    vektor_TFIDF=np.array([])
    for baris in matriks_TF:
        baris_tfidf=np.multiply(baris,baris_IDF)
        vektor_TFIDF=np.concatenate((vektor_TFIDF,baris_tfidf), axis=0)
    matriks_TFIDF = vektor_TFIDF.reshape(df_teks.shape[0], jumlah_kosa_kata)
    matriks_TFIDF = normalize(matriks_TFIDF)
    # Membuat dataframe TF-IDF
    df_TF_IDF = pd.DataFrame(matriks_TFIDF, columns=kosa_kata, index=df_teks.text.tolist())
    return df_TF_IDF

**Contoh Implementasi Fungsi `TF_IDF()`**

In [30]:
df_teks

text
0  Selamat Pagi Matematika UAD
1       Selamat Pagi Indonesia

In [31]:
df_TF_IDF=TF_IDF(df_teks)
df_TF_IDF

indonesia  matematika      pagi   selamat  \
Selamat Pagi Matematika UAD   0.000000    0.576152  0.409937  0.409937   
Selamat Pagi Indonesia        0.704909    0.000000  0.501549  0.501549   

                                  uad  
Selamat Pagi Matematika UAD  0.576152  
Selamat Pagi Indonesia       0.000000

### Perbandingan dengan Scikit Learn Library

Sebenarnya, kita bisa menghasilkan matriks TFIDF dengan menggunakan Library Scikit Learn pada Class `TfidfVectorizer`

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

corpus = ['Selamat Pagi Matematika UAD','Selamat Pagi Indonesia']

X = vectorizer.fit_transform(corpus)

df_TFIDF_SL = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names(), index=corpus)
df_TFIDF_SL

indonesia  matematika      pagi   selamat  \
Selamat Pagi Matematika UAD   0.000000    0.576152  0.409937  0.409937   
Selamat Pagi Indonesia        0.704909    0.000000  0.501549  0.501549   

                                  uad  
Selamat Pagi Matematika UAD  0.576152  
Selamat Pagi Indonesia       0.000000

Hasil fungsi yang kita buat dari dasar sama dengan `TfidfVectorizer` dari Library Scikit Learn